services:
  web:
    image: 
    ports:
      - "80:80"
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025" # Mailpit web interface
      - "1025:1025" # SMTP port
    environment:
      - MAILPIT_SMTP_PORT=1025
      - MAILPIT_HTTP_PORT=8025