color: null
fieldLayouts:
  f1bb0251-fc41-4387-80f1-b90d9bbaaba0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T12:30:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 72be5c17-271c-4094-882c-c668aed0adc9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T12:32:12+00:00'
            elementCondition: null
            fieldUid: 6fa0c7ef-bc6d-4121-8057-43a1cbe549eb # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5a1ced9-9a82-4ca4-92bd-500b438117ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T12:32:12+00:00'
            elementCondition: null
            fieldUid: 93ebd873-a0a2-437b-a0d7-a50ca4be4d53 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c7b7e8f-10c6-454f-9109-92711405b262
            userCondition: null
            warning: null
            width: 100
        name: Banner
        uid: 4501885d-e911-4131-ab25-0d47626eb3f7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T14:23:06+00:00'
            elementCondition: null
            fieldUid: 6576f601-4ad6-4449-b1f7-e9a7b6e6ea7d # Deelnemers
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 189e1936-9701-43ab-8a3c-f0d7c44757cc
            userCondition: null
            warning: null
            width: 100
        name: Beschikbaarheid
        uid: 74b68857-db03-47bb-b6d3-c1421f09d5bd
        userCondition: null
handle: beschikbaarheid
hasTitleField: true
icon: ''
name: ' Beschikbaarheid'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
