color: null
fieldLayouts:
  1bfbfa0c-e185-4e55-a2c3-1fef2a163906:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T14:18:30+00:00'
            elementCondition: null
            fieldUid: 1fba546c-8988-41ac-841e-dd0018f94985 # Spelers
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39603ea9-6ac3-40ef-8769-842e981d641e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T14:20:14+00:00'
            elementCondition: null
            fieldUid: e7ef9ec4-ade1-408b-9c33-eb61f8316000 # Spelerstatus
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6d0d1ea-15ef-4273-991c-c6a9f1f6b2a3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T14:18:30+00:00'
            elementCondition: null
            fieldUid: aee3c4de-37c9-4d3a-883f-ebbac655e419 # Planningstatus
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99996434-00f3-4bfc-a538-5b8ae25d568b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1673daf6-4501-47b3-998a-397cc69ff621
        userCondition: null
handle: deelnemers
hasTitleField: false
icon: ''
name: Deelnemers
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
