color: blue
fieldLayouts:
  6ed1a424-92c8-4107-baa4-cb326585b44f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-11T11:06:56+00:00'
            elementCondition: null
            fieldUid: 93ebd873-a0a2-437b-a0d7-a50ca4be4d53 # Image
            handle: banner_image
            includeInCards: false
            instructions: null
            label: banner_image
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8450ee00-a408-4af0-b379-766832b86973
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T10:59:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 42d90d70-0bd3-4647-8b5b-b62a28cc3a13
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-11T11:06:56+00:00'
            elementCondition: null
            fieldUid: 6fa0c7ef-bc6d-4121-8057-43a1cbe549eb # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5d9d3a8-8a26-42b9-989b-8ed15d14949b
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: b4aed88c-e2ae-46c2-98ce-713e40715e12
        userCondition: null
handle: drankenregistratie
hasTitleField: true
icon: cup-straw
name: Drankenregistratie
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
