color: null
fieldLayouts:
  b930e95a-f93c-4ce3-818b-5151fa4c913e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T10:58:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f425d428-bbc6-46b8-bc3e-722434080894
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T10:58:25+00:00'
            elementCondition: null
            fieldUid: b179a167-1bb1-4794-acb3-26224f6b33b7
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46ac349a-72bd-40b0-a5f2-416f9ed231f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T10:58:25+00:00'
            elementCondition: null
            fieldUid: e0fe4a95-5a6e-4260-a633-8d65ec4d2715
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9152d175-1730-4af6-b055-bee5aedaa3dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T10:58:25+00:00'
            elementCondition: null
            fieldUid: bb631c41-7448-4870-9182-2ccb95691176 # Emailadres
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e5d69fe-0231-4974-b1df-4b31f701f536
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T10:58:25+00:00'
            elementCondition: null
            fieldUid: dc8e3d48-33c2-4fb2-a99c-7ade8c40c048
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de3ecc3e-757c-4a09-9ad1-45122dc0b024
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T10:58:25+00:00'
            elementCondition: null
            fieldUid: 667217cb-2377-42e5-9960-0713cfb1262e # Rol
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d0936a7-3f63-40db-bae0-5577acdbdc33
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c93eef3f-afa6-41fb-87e0-0f13ffbde624
        userCondition: null
handle: gebruikers
hasTitleField: true
icon: ''
name: Gebruikers
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{voornaam} {achternaam}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
