color: null
fieldLayouts:
  7ee9c971-eb51-422b-aa4b-61b909c959d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-06T11:56:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4fee2d0c-5e4d-46b1-8acb-02ce5dcf8dc2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 223ade8d-90fd-4809-a39c-b30ee22426b2
        userCondition: null
handle: mailTest
hasTitleField: true
icon: null
name: 'Mail test'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
