color: null
fieldLayouts:
  fbeb8c69-0072-46fe-9982-a5a02af6cc60:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-12T11:08:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f2c3a34a-33d5-487c-8b85-7061c09a612f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T14:59:49+00:00'
            elementCondition: null
            fieldUid: 955c2d2c-ae7f-4c24-8d64-faf6d31ab9fa # Wedstrijd
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90f067a1-74cc-4e88-9489-73b8c27f8041
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T14:22:55+00:00'
            elementCondition: null
            fieldUid: 64e0c57c-083f-4231-994c-328a261a8126 # Datum
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04df8e9c-1282-415a-9293-411ead113393
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b25574b7-36ca-413b-a875-537187775a6b
        userCondition: null
handle: matches
hasTitleField: true
icon: null
name: Matches
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{wedstrijd}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
