color: null
fieldLayouts:
  d5a0983a-8571-4a69-9755-e3ae4744a55c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-10T14:48:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ff7ebbfb-b268-4570-aa2c-3b2358f4d5ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T14:55:49+00:00'
            elementCondition: null
            fieldUid: 7d66023b-3cf3-4e8d-8404-ea3521f53dc4 # Speler
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63a4b509-1818-4c59-be58-be24eda9f490
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T15:01:07+00:00'
            elementCondition: null
            fieldUid: 245aa79c-664f-4668-ac0b-dc21396c39fd # Matches
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7dd8d08-ef37-4388-80b0-4f765ae1c443
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T14:55:49+00:00'
            elementCondition: null
            fieldUid: e7ef9ec4-ade1-408b-9c33-eb61f8316000 # Spelerstatus
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcfc7cb8-3253-4661-b53e-4b632dcc2a6e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a24d5ae-69aa-41db-a7d6-2512f584156a
        userCondition: null
handle: planning
hasTitleField: true
icon: null
name: Planning
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
