color: rose
fieldLayouts:
  9cf80d8f-b509-4a84-a647-62d9d73ee39a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T13:44:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 02009988-771b-4180-8d65-cb49082760f6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 57e5dacc-5c4e-4acc-9219-ab92aa524c7b
        userCondition: null
handle: register
hasTitleField: true
icon: user
name: Register
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
