color: yellow
fieldLayouts:
  1ff151c1-c4f4-42bd-b092-e24b95e5c68d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-27T14:12:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 670c302b-f1cd-4632-b406-66547b020d60
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-27T14:15:34+00:00'
            elementCondition: null
            fieldUid: b4487ccc-ea00-4331-accc-868e5d4da208 # Stash user
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcacef53-f78e-4af0-960c-06f7e5d35936
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-27T14:15:34+00:00'
            elementCondition: null
            fieldUid: 0fc8ebe8-f7ec-4241-bc21-3fc7900074c9 # Stash items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2916af9-7f92-4cf1-a6a8-23e1cdca6e95
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-27T14:15:34+00:00'
            elementCondition: null
            fieldUid: 6b79a1a5-f740-4010-8185-58280ab8d7bd # Stash status
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7f62dc8-558e-46e3-b7e9-d238b40a8f0b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-08T12:15:26+00:00'
            elementCondition: null
            fieldUid: f943400f-82ac-4ca3-8f8e-46f1a8cec813 # stash guest name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f807ced-dc57-4e7d-b442-d9194c758f46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-08T11:59:24+00:00'
            elementCondition: null
            fieldUid: 3d87f6ff-d6d3-44e9-941e-97f94304ce72 # stash is guest
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7ceb612-7e94-41d9-b479-9ce1dbf86e18
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50cde072-af74-4177-950f-0aa01187a8bc
        userCondition: null
handle: stash
hasTitleField: true
icon: bag-shopping
name: Stash
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
