color: yellow
fieldLayouts:
  748b4eb8-bd6d-4027-8680-a9bb28151ff5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-27T14:06:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 253fe8fa-315e-4b4d-b187-abfa0a36573c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-27T14:11:45+00:00'
            elementCondition: null
            fieldUid: 74e47521-7291-4e41-acad-9ce0f4e319c8 # Drankje
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d97387f-d575-46f2-9813-2a6fbd7d6ea3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-27T14:11:45+00:00'
            elementCondition: null
            fieldUid: b1b5283f-c9ee-434b-b009-9c073788101d # Prijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f0dcb20-7949-4422-87f3-60b05a7e55a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-27T14:11:45+00:00'
            elementCondition: null
            fieldUid: 73cdf7a9-3911-4520-a836-63707d21669e # Amount
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a51883f2-e016-4d24-a6e4-af645a1b6ec3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f96b7bf9-c195-48f1-8aac-c5caee4004f4
        userCondition: null
handle: stash_items
hasTitleField: true
icon: album-collection
name: 'Stash items'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{drankjes.title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
