color: null
fieldLayouts:
  2f9a5da1-dc7e-43bb-872b-01075009ab63:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: e545e29f-a84f-4c9a-9d84-8fa5eaeaa445
        userCondition: null
handle: winkelmandje
hasTitleField: false
icon: null
name: Winkelmandje
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
