allowPublicRegistration: true
deactivateByDefault: false
defaultGroup: 637a3d3c-476e-4943-8eab-36dd28c4aaa3
photoSubpath: null
photoVolumeUid: null
require2fa: false
requireEmailVerification: true
validateOnPublicRegistration: false
