columnSuffix: null
handle: betaald
instructions: null
name: 'Betaald?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
