columnSuffix: null
handle: planningstatus
instructions: null
name: Planningstatus
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Afwachting
        -
          - value
          - afwachting
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Geaccepteerd
        -
          - value
          - geaccepteerd
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
