columnSuffix: null
handle: ploeg
instructions: null
name: Ploeg
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - A
        -
          - value
          - a
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - B
        -
          - value
          - b
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - C
        -
          - value
          - c
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
