columnSuffix: null
handle: rol
instructions: null
name: Rol
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Lid
        -
          - value
          - lid
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Gast
        -
          - value
          - gast
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Beheerder
        -
          - value
          - beheerder
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
