columnSuffix: null
handle: spelerstatus
instructions: null
name: Spelerstatus
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Wachtend
        -
          - value
          - wachtend
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bevestigd
        -
          - value
          - bevestigd
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
