columnSuffix: null
handle: stash_user
instructions: null
name: 'Stash user'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - admins
    - 'group:637a3d3c-476e-4943-8eab-36dd28c4aaa3' # Spelers
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Users
