dateModified: 1734014341
elementSources:
  studioespresso\molliepayments\elements\Payment:
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - email
        - amount
        - status
        - dateCreated
      type: native
email:
  fromEmail: lukasvannuffel02@gmail.com
  fromName: werkstuk-tafeltennis-lukasvannuffel
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@assetBasePath/images'
    type: craft\fs\Local
    url: '@assetBaseUrl/images'
meta:
  __names__:
    1a6f7e14-d517-4e48-aeca-ae1c2d532c93: Home # Home
    1cd4c70f-bf52-4046-b725-ea42005ee9aa: Home # Home
    1fba546c-8988-41ac-841e-dd0018f94985: Spelers # Spelers
    5c93ee1d-ec63-4cf7-ba9d-7111d3aa0f73: Rekeningen # Rekeningen
    6fa0c7ef-bc6d-4121-8057-43a1cbe549eb: Subtitle # Subtitle
    8c96c385-7ae2-4955-a437-f910e682658e: Beschikbaarheid # Beschikbaarheid
    8f421a20-8d59-427d-912d-74cd9a1a051f: 'Mijn rekening' # Mijn rekening
    33fb3089-2bd6-474e-9c53-ca57f6c6bb77: 'Public Schema' # Public Schema
    34efd35b-67c2-4437-8ed9-9ae98f2ff641: Gebruiker # Gebruiker
    64e0c57c-083f-4231-994c-328a261a8126: Datum # Datum
    65debaad-47e9-4f45-876e-19998c8823e0: Images # Images
    74e47521-7291-4e41-acad-9ce0f4e319c8: Drankje # Drankje
    93ebd873-a0a2-437b-a0d7-a50ca4be4d53: Image # Image
    637a3d3c-476e-4943-8eab-36dd28c4aaa3: Spelers # Spelers
    979a2e8a-14f1-4bf4-972a-a6f8537ed8fa: Login # Login
    3624d35f-9f04-4fc6-ae1c-0d6b1cf75c20: Speeldagen # Speeldagen
    271816ba-39ea-4493-b88d-2fba50eab52c: Ploeg # Ploeg
    667217cb-2377-42e5-9960-0713cfb1262e: Rol # Rol
    02615120-926d-4e16-8cc8-3c1fd7205d39: Register # Register
    ac383a6b-ebac-4924-a5cd-c296993ed2de: werkstuk-tafeltennis-lukasvannuffel # werkstuk-tafeltennis-lukasvannuffel
    ad7cf296-5131-49cd-b076-f65b65700d3a: Register # Register
    ae9384bd-229d-4572-b377-d5b428249764: Drankjes # Drankjes
    b1b5283f-c9ee-434b-b009-9c073788101d: Prijs # Prijs
    b81bc918-86b4-4998-abe1-b49438f074cc: Profile # Profile
    b14077b8-fe60-4309-8204-c3e4f04abd23: Rekeningen # Rekeningen
    bb631c41-7448-4870-9182-2ccb95691176: Emailadres # Emailadres
    c9bd182c-cb7b-4d2c-95aa-3ca8e1f6c2e2: Aantal # Aantal
    c29ffaff-3889-4344-a4eb-90d3c9b4daad: Drankenregistratie # Drankenregistratie
    c963e5ce-35b1-4760-b7b4-ade821948fb5: Login # Login
    cd386740-90bb-494c-9ed1-090aad5aead7: Drankenregistratie # Drankenregistratie
    d6f691ca-05ab-4d3d-851a-3974878a4a7a: Gebruikers # Gebruikers
    d9c2dacc-097d-4008-ae8d-342559a5d4dc: Login # Login
    d18ddf66-9e9c-4f66-a02c-8195fdda702d: Profile # Profile
    d94afcc3-617e-4ee5-9a41-d22e68040c74: 'Mijn rekening' # Mijn rekening
    e0b4b115-08c1-4bec-b6aa-a11f85202928: 'Betaald?' # Betaald?
    e3dd8d5e-7b15-4c2f-a1b6-9c8670dcc18c: Drankjes # Drankjes
    f4b1d9ae-cf5d-4862-be19-a850752f1182: werkstuk-tafeltennis-lukasvannuffel # werkstuk-tafeltennis-lukasvannuffel
    f358877f-62fa-4726-9045-c6afb46fe030: bio # bio
plugins:
  graphql-authentication:
    edition: standard
    enabled: true
    licenseKey: ZSF5ESBFHTM8PNY203MSEO8N
    schemaVersion: 1.3.0
  mollie-payments:
    edition: standard
    enabled: true
    licenseKey: JGHTYR2SDQ519C99GYYW3RXP
    schemaVersion: 5.0.0
    settings:
      apiKey: test_KSysEm8rvFNfNudt8ajG8mw5BpD8sH
      manageSubscriptionEmailPath: ''
      manageSubscriptionEmailSubject: ''
      manageSubscriptionRoute: ''
      pluginLabel: Payments
system:
  edition: pro
  live: true
  name: werkstuk-tafeltennis-lukasvannuffel
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
