dateModified: 1735913577
elementSources:
  studioespresso\molliepayments\elements\Payment:
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - email
        - amount
        - status
        - dateCreated
      type: native
email:
  fromEmail: lukasvannuffel02@gmail.com
  fromName: werkstuk-tafeltennis-lukasvannuffel
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@assetBasePath/images'
    type: craft\fs\Local
    url: '@assetBaseUrl/images'
meta:
  __names__:
    0fc8ebe8-f7ec-4241-bc21-3fc7900074c9: 'Stash items' # Stash items
    1a6f7e14-d517-4e48-aeca-ae1c2d532c93: Home # Home
    1cd4c70f-bf52-4046-b725-ea42005ee9aa: Home # Home
    1fba546c-8988-41ac-841e-dd0018f94985: Spelers # Spelers
    5c93ee1d-ec63-4cf7-ba9d-7111d3aa0f73: Rekeningen # Rekeningen
    05dba92f-d3ec-482e-9de3-ad49e365a941: Deelnemers # Deelnemers
    6b0d1ed3-174c-459a-b143-37d8a5a63a05: Stash # Stash
    6b79a1a5-f740-4010-8185-58280ab8d7bd: 'Stash status' # Stash status
    6fa0c7ef-bc6d-4121-8057-43a1cbe549eb: Subtitle # Subtitle
    8f421a20-8d59-427d-912d-74cd9a1a051f: 'Mijn rekening' # Mijn rekening
    34efd35b-67c2-4437-8ed9-9ae98f2ff641: Gebruiker # Gebruiker
    64e0c57c-083f-4231-994c-328a261a8126: Datum # Datum
    65debaad-47e9-4f45-876e-19998c8823e0: Images # Images
    73cdf7a9-3911-4520-a836-63707d21669e: Amount # Amount
    74e47521-7291-4e41-acad-9ce0f4e319c8: Drankje # Drankje
    93ebd873-a0a2-437b-a0d7-a50ca4be4d53: Image # Image
    626db96f-3c5c-4fee-a45e-fcf1f766f7a4: Voorraad # Voorraad
    758e3b57-8c91-48e2-8bf2-29f90f9606f5: Winkelmandje # Winkelmandje
    979a2e8a-14f1-4bf4-972a-a6f8537ed8fa: Login # Login
    3624d35f-9f04-4fc6-ae1c-0d6b1cf75c20: Speeldagen # Speeldagen
    6529c225-c06c-4267-ad0e-9f64b3e9bbf3: Referentie # Referentie
    6576f601-4ad6-4449-b1f7-e9a7b6e6ea7d: Deelnemers # Deelnemers
    271816ba-39ea-4493-b88d-2fba50eab52c: Ploeg # Ploeg
    613564dc-a9af-44b0-89c7-c582a3869d3c: Beschikbaarheid # Beschikbaarheid
    667217cb-2377-42e5-9960-0713cfb1262e: Rol # Rol
    02615120-926d-4e16-8cc8-3c1fd7205d39: Register # Register
    52105425-0e0d-46b8-b25d-6886ea47cd57: Stash # Stash
    a203f5e7-ccb7-428a-b183-8768ebe2699f: 'Public Schema' # Public Schema
    ac383a6b-ebac-4924-a5cd-c296993ed2de: werkstuk-tafeltennis-lukasvannuffel # werkstuk-tafeltennis-lukasvannuffel
    ad7cf296-5131-49cd-b076-f65b65700d3a: Register # Register
    ae9384bd-229d-4572-b377-d5b428249764: Drankjes # Drankjes
    aee3c4de-37c9-4d3a-883f-ebbac655e419: Planningstatus # Planningstatus
    b1b5283f-c9ee-434b-b009-9c073788101d: Prijs # Prijs
    b81bc918-86b4-4998-abe1-b49438f074cc: Profile # Profile
    b4487ccc-ea00-4331-accc-868e5d4da208: 'Stash user' # Stash user
    b14077b8-fe60-4309-8204-c3e4f04abd23: Rekeningen # Rekeningen
    bb631c41-7448-4870-9182-2ccb95691176: Emailadres # Emailadres
    c9bd182c-cb7b-4d2c-95aa-3ca8e1f6c2e2: Aantal # Aantal
    c29ffaff-3889-4344-a4eb-90d3c9b4daad: Drankenregistratie # Drankenregistratie
    c963e5ce-35b1-4760-b7b4-ade821948fb5: Login # Login
    cd386740-90bb-494c-9ed1-090aad5aead7: Drankenregistratie # Drankenregistratie
    d9c2dacc-097d-4008-ae8d-342559a5d4dc: Login # Login
    d18ddf66-9e9c-4f66-a02c-8195fdda702d: Profile # Profile
    d94afcc3-617e-4ee5-9a41-d22e68040c74: 'Mijn rekening' # Mijn rekening
    e0b4b115-08c1-4bec-b6aa-a11f85202928: 'Betaald?' # Betaald?
    e3dd8d5e-7b15-4c2f-a1b6-9c8670dcc18c: Drankjes # Drankjes
    e7ef9ec4-ade1-408b-9c33-eb61f8316000: Spelerstatus # Spelerstatus
    ec0604d1-e7bf-48dc-ad2c-2b5f5463ec14: ' Beschikbaarheid' #  Beschikbaarheid
    f4b1d9ae-cf5d-4862-be19-a850752f1182: werkstuk-tafeltennis-lukasvannuffel # werkstuk-tafeltennis-lukasvannuffel
    f358877f-62fa-4726-9045-c6afb46fe030: bio # bio
    ff9d7c3e-d31f-403c-971a-34a2eacb98a9: 'Stash items' # Stash items
plugins:
  graphql-authentication:
    edition: standard
    enabled: false
    licenseKey: ZSF5ESBFHTM8PNY203MSEO8N
    schemaVersion: 1.3.0
  mollie-payments:
    edition: standard
    enabled: true
    licenseKey: JGHTYR2SDQ519C99GYYW3RXP
    schemaVersion: 5.0.0
    settings:
      apiKey: test_djWefDkc3S3REesdVJKrWuadMRNNhJ
      manageSubscriptionEmailPath: ''
      manageSubscriptionEmailSubject: ''
      manageSubscriptionRoute: ''
      pluginLabel: Payments
system:
  edition: pro
  live: true
  name: werkstuk-tafeltennis-lukasvannuffel
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: Europe/Brussels
