defaultPlacement: end
enableVersioning: true
entryTypes:
  - ec0604d1-e7bf-48dc-ad2c-2b5f5463ec14 #  Beschikbaarheid
handle: beschikbaarheid
maxAuthors: 1
name: Beschikbaarheid
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: beschikbaarheid/_entry.twig
    uriFormat: beschikbaarheid
type: channel
