defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1a6f7e14-d517-4e48-aeca-ae1c2d532c93 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: home/_entry.twig
    uriFormat: home
type: single
