defaultPlacement: end
enableVersioning: true
entryTypes:
  - d9c2dacc-097d-4008-ae8d-342559a5d4dc # Login
handle: login
maxAuthors: 1
name: Login
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: pages/Login/login.twig
    uriFormat: 'login/{slug}'
type: channel
