defaultPlacement: end
enableVersioning: true
entryTypes:
  - 047ab60c-b5fe-484a-b4de-78fefacc25c4 # Mail test
handle: mailTest
maxAuthors: 1
name: 'Mail test'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: mail-test/_entry.twig
    uriFormat: mail-test
type: single
