defaultPlacement: end
enableVersioning: true
entryTypes:
  - d94afcc3-617e-4ee5-9a41-d22e68040c74 # Mijn rekening
handle: mijnRekening
maxAuthors: 1
name: 'Mijn rekening'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: mijn-rekening/betalen.twig
    uriFormat: mijn-rekening
type: single
