defaultPlacement: end
enableVersioning: true
entryTypes:
  - 99e9512d-0dd0-4872-96e8-92f1691289b5 # Notificaties
handle: notificaties
maxAuthors: 1
name: Notificaties
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: home/_entry.twig
    uriFormat: 'notificaties/{slug}'
type: channel
