defaultPlacement: end
enableVersioning: true
entryTypes:
  - 946e1707-aedf-4de1-8d7a-af57d5412667 # Planning
handle: planning_section
maxAuthors: 1
name: Planning
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: planning/_entry.twig
    uriFormat: 'planning/{slug}'
type: channel
