defaultPlacement: end
enableVersioning: true
entryTypes:
  - d18ddf66-9e9c-4f66-a02c-8195fdda702d # Profile
handle: profile
maxAuthors: 1
name: Profile
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: profile/_entry.twig
    uriFormat: 'profile/{slug}'
type: channel
