defaultPlacement: end
enableVersioning: true
entryTypes:
  - ad7cf296-5131-49cd-b076-f65b65700d3a # Register
handle: register
maxAuthors: 1
name: Register
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: register/_entry.twig
    uriFormat: register
type: single
