defaultPlacement: end
enableVersioning: true
entryTypes:
  - d94afcc3-617e-4ee5-9a41-d22e68040c74 # Mijn rekening
handle: rekeningen
maxAuthors: 1
name: Rekeningen
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: pages/Rekeningen/rekeningen.twig
    uriFormat: 'rekeningen/{slug}'
type: channel
