defaultPlacement: end
enableVersioning: true
entryTypes:
  - 75bf3c78-2512-4089-8dec-1fefc0f3f317 # Reset password
handle: resetPassword
maxAuthors: 1
name: 'Reset password'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: reset-password/_entry.twig
    uriFormat: reset-password
type: single
