defaultPlacement: end
enableVersioning: true
entryTypes:
  - ad99b810-d13e-413a-bb30-e9b27a7f8e37 # Wedstrijden
handle: wedstrijden
maxAuthors: 1
name: Wedstrijden
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac383a6b-ebac-4924-a5cd-c296993ed2de: # werkstuk-tafeltennis-lukasvannuffel
    enabledByDefault: true
    hasUrls: true
    template: wedstrijden/_entry.twig
    uriFormat: 'wedstrijden/{slug}'
type: channel
